"""Add carousel_type to content table

Revision ID: 6c58e33ca99d
Revises: bcf5c936b184
Create Date: 2026-03-28 11:19:14.126643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c58e33ca99d'
down_revision: Union[str, None] = 'bcf5c936b184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('carousel_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'carousel_type')
    # ### end Alembic commands ###
