"""Add location_type to location table

Revision ID: 7e89c0797948
Revises: 6c58e33ca99d
Create Date: 2026-03-28 15:53:07.736167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e89c0797948'
down_revision: Union[str, None] = '6c58e33ca99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('location_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'location_type')
    # ### end Alembic commands ###
