"""Add bio and avatar_url to author

Revision ID: b4dd47fcebfe
Revises: 7e89c0797948
Create Date: 2026-03-28 16:07:56.968845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dd47fcebfe'
down_revision: Union[str, None] = '7e89c0797948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('author', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.drop_column('author', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('author', 'avatar_url')
    op.drop_column('author', 'bio')
    # ### end Alembic commands ###
