"""Add TOTP columns

Revision ID: e52b0bb7cf85
Revises: b4dd47fcebfe
Create Date: 2026-04-02 13:24:48.130067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52b0bb7cf85'
down_revision: Union[str, None] = 'b4dd47fcebfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('is_totp_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
